# OWNER: P1 -- see docs/WORK.md. Do not edit if you are not P1.
"""Peer table read and write, for the dashboard's setup panel.

Addresses change every time the network does -- a different campus room, a
phone hotspot, a laptop that got a new DHCP lease -- and four people editing
four copies of peers.yaml by hand is how a demo dies ten minutes before it is
due. This lets the table be typed once in the dashboard and written out.

peers.yaml is gitignored on purpose (docs/SETUP.md): addresses are per-person
and per-network, and committing one guarantees three of the four are wrong.
"""
from __future__ import annotations

import ipaddress
import re
import socket
from pathlib import Path
from typing import Any

import yaml

#: config/ next to the repo root, resolved from this file rather than from the
#: working directory -- a node started from anywhere must write the same file.
CONFIG_DIR = Path(__file__).resolve().parents[2] / "config"
PEERS_PATH = CONFIG_DIR / "peers.yaml"

#: Peer names are single path segments: no '/', so a peer can never be written
#: where a child path belongs. Same charset as docs/PROTOCOL.md addressing.
PEER_NAME = re.compile(r"^[a-z0-9_]+$")

#: Hostnames as well as literal IPs -- a laptop announcing itself over mDNS as
#: `aditya-laptop.local` is a legitimate peer address.
HOSTNAME = re.compile(r"^[a-z0-9]([a-z0-9\-.]{0,251}[a-z0-9])?$", re.IGNORECASE)

KNOWN_ROLES = ("planner", "executor", "reviewer", "verifier")


class ConfigError(ValueError):
    """The submitted peer table is not usable. Message is shown to the user."""


def validate_host(host: str) -> str:
    """An IP literal or a hostname. Anything else is rejected.

    This value ends up in a URL the node will POST to, so it is validated
    rather than trusted: it arrives over HTTP from a browser, which makes it
    input from outside the system regardless of who is typing.
    """
    host = str(host).strip()
    if not host:
        raise ConfigError("host is empty")
    try:
        ipaddress.ip_address(host)
        return host
    except ValueError:
        pass
    if not HOSTNAME.match(host):
        raise ConfigError(f"{host!r} is neither an IP address nor a valid hostname")
    return host


def validate_port(port: Any) -> int:
    try:
        value = int(port)
    except (TypeError, ValueError) as exc:
        raise ConfigError(f"port {port!r} is not a number") from exc
    if not 1 <= value <= 65535:
        raise ConfigError(f"port {value} is outside 1-65535")
    return value


def validate_peers(peers: Any) -> dict[str, dict[str, Any]]:
    """Normalise and check a whole peer table.

    Rejects duplicate host:port pairs. Two peers on one address is not a typo
    the system can survive: the second node fails to bind, and the failure
    surfaces as an unrelated timeout on a third machine.
    """
    if not isinstance(peers, dict) or not peers:
        raise ConfigError("peer table is empty")

    cleaned: dict[str, dict[str, Any]] = {}
    seen: dict[tuple[str, int], str] = {}

    for name, cfg in peers.items():
        if not PEER_NAME.match(str(name)):
            raise ConfigError(f"{name!r} is not a valid peer name ([a-z0-9_], no '/')")
        if not isinstance(cfg, dict):
            raise ConfigError(f"{name}: expected host/port/role/model")

        host = validate_host(cfg.get("host", ""))
        port = validate_port(cfg.get("port", 8000))
        if (host, port) in seen:
            raise ConfigError(f"{name} and {seen[(host, port)]} share {host}:{port}")
        seen[(host, port)] = str(name)

        cleaned[str(name)] = {
            "host": host,
            "port": port,
            "role": str(cfg.get("role") or "executor"),
            "model": str(cfg.get("model") or "mock"),
        }
    return cleaned


def to_yaml(peers: dict[str, dict[str, Any]], defaults: dict[str, Any] | None = None) -> str:
    """The file's exact contents -- also what the dashboard shows for copying.

    The other three laptops need this byte-for-byte. Whoever types the
    addresses can write it locally; everyone else pastes.
    """
    body = {
        "peers": peers,
        "defaults": defaults or {"max_depth": 3, "budget": {"usd": 0.50, "turns": 12}},
    }
    header = (
        "# Generated by the Samvad dashboard. Every device needs THIS FILE,\n"
        "# byte-identical -- a peer table that disagrees routes messages into\n"
        "# the void and the failure looks like a network problem.\n"
        "#\n"
        "# Gitignored: addresses are per-network and change when the wifi does.\n"
    )
    return header + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)


def write_peers(peers: dict[str, dict[str, Any]], defaults: dict[str, Any] | None = None) -> Path:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    PEERS_PATH.write_text(to_yaml(peers, defaults), encoding="utf-8")
    return PEERS_PATH


def read_peers() -> dict[str, Any] | None:
    if not PEERS_PATH.exists():
        return None
    return yaml.safe_load(PEERS_PATH.read_text(encoding="utf-8")) or None


def local_addresses() -> list[str]:
    """This machine's own LAN addresses, offered as a starting point.

    Typing your own IP wrong is the most common way the table ends up broken,
    and it is the one value the node can fill in for you.
    """
    found: list[str] = []
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # No packet is sent; connect() on UDP just picks the route the kernel
        # would use, which is how you learn which interface faces the LAN.
        probe.connect(("8.8.8.8", 80))
        found.append(probe.getsockname()[0])
    except OSError:
        pass
    finally:
        probe.close()

    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            addr = info[4][0]
            if addr not in found and not addr.startswith("127."):
                found.append(addr)
    except OSError:
        pass
    return found


#: Generous on purpose. Measured on Windows: a REFUSED connection to
#: 127.0.0.1 takes ~2.0s to report ConnectionRefusedError, so a 2s timeout
#: fires first and the refusal is misreported as a timeout. That is the one
#: confusion that actually costs someone an afternoon -- it says "your network
#: isolates clients, find another one" when the truth is "that node is not
#: started yet". Better to wait longer and answer correctly.
PROBE_TIMEOUT = 5.0


async def probe(host: str, port: int, timeout: float = PROBE_TIMEOUT) -> str:
    """reachable | refused | timeout -- the distinction that matters.

    REFUSED means the path works and nothing is listening yet: normal before a
    peer starts its node. TIMEOUT means the host cannot be reached at all, and
    on shared wifi that is almost always AP/client isolation, which no amount
    of code will fix. Same diagnostic as scripts/netcheck.py, exposed to the UI
    so it can be run without a terminal.

    ConnectionRefusedError is caught before the timeout branch, and the timeout
    is set long enough that a slow refusal wins the race -- see PROBE_TIMEOUT.
    """
    import asyncio

    try:
        fut = asyncio.open_connection(host, port)
        _, writer = await asyncio.wait_for(fut, timeout)
        writer.close()
        return "reachable"
    except ConnectionRefusedError:
        return "refused"
    except (TimeoutError, OSError):
        return "timeout"
