"""Contract: state. Seam between P3 and P1/P2."""
import pytest

pytestmark = pytest.mark.skip(reason="week 1: needs BlobStore and MessageLog")


def test_same_bytes_produce_one_blob_and_same_ref(): ...
def test_unknown_ref_returns_none(): ...
def test_replay_restores_conversation_after_restart(): ...
def test_replay_order_is_lamport_not_timestamp(): ...
def test_backpressure_trips_above_ninety_percent(): ...
