"""Contract: the wire. Seam between P1 and everyone.

The 202 test is the important one -- it is the invariant that makes the whole
architecture asynchronous rather than four blocked HTTP clients.
"""
import pytest

pytestmark = pytest.mark.skip(reason="week 1: needs InProcTransport")


def test_post_message_returns_202_without_awaiting_handler(): ...
def test_duplicate_message_id_returns_cached_and_does_not_redispatch(): ...
def test_bad_signature_returns_401(): ...
def test_longest_prefix_routes_child_to_its_peer(): ...
def test_same_envelope_over_all_three_transports(): ...
