"""Contract: the envelope. Owner P1, but everyone depends on it.

Write these BEFORE protocol.py. They are the executable form of
docs/PROTOCOL.md and the only thing that catches a confident, incompatible
reading of the schema.
"""
import pytest

pytestmark = pytest.mark.skip(reason="week 1: write protocol.py together first")


def test_version_mismatch_is_rejected_not_coerced(): ...
def test_signature_roundtrip(): ...
def test_tampered_body_fails_verification(): ...
def test_timestamp_outside_replay_window_rejected(): ...
def test_lamport_observe_takes_max_plus_one(): ...
def test_child_budget_slices_sum_to_at_most_parent(): ...
def test_child_cannot_raise_max_depth(): ...
def test_path_depth_must_equal_spawn_depth(): ...
def test_root_task_change_within_conversation_rejected(): ...
def test_artifact_ref_must_be_sha256(): ...
